// menu
export const MENU_LOAD_BRAND = 'MENU_LOAD_BRAND';
export const MENU_LOAD_PRIMARY = 'MENU_LOAD_PRIMARY';
export const MENU_LOAD_SECONDARY = 'MENU_LOAD_SECONDARY';
export const MENU_LOAD_ACCOUNT = 'MENU_LOAD_ACCOUNT';

// view
export const VIEW_LOAD_COLORS = 'VIEW_LOAD_COLORS';
export const VIEW_SET_SITE = 'VIEW_SET_SITE';
